### PR TITLE
Introduction changes

### PR DESCRIPTION
**Pull request by lepilmen**
New logical content flow for the 101 intro,
Fixed minor devtools error from ./vendor/scroller.js

- - -
This change is [Reviewable](https://reviewable.io/reviews/kube-HPC/kube-HPC.github.io/38)

### CODE REVIEW

**Review by golanha — CHANGES_REQUESTED** [review]
> Reviewed 10 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-HPC/kube-HPC.github.io/38)* status: 10 of 12 files reviewed, 14 unresolved discussions (waiting on @lepilmen and @zivglik)

___
*[`site/learn/IntroductionV2.md` line 37 at r1](https://reviewable.io/reviews/kube-HPC/kube-HPC.github.io/38#-NQR2E8y8uGiT_rR0ZPO:-NQR2E8y8uGiT_rR0ZPP:b-gcn3f4) ([raw file](https://github.com/kube-HPC/kube-HPC.github.io/blob/e50cd9f1561aa2f9c54f79fddc3aa6139d623254/site/learn/IntroductionV2.md#L37)):*
> ```Markdown
> 
> ## Getting started
> - HKube is available in 3 formats, [UI](#getting-started), [CLI](/learn/api/#Cli) and [RESTFUL-API](/learn/api/#restful-api).
> ```

shouldn't be a link
[UI] <s>(#getting-started)</s>



_Code quote:_
```Markdown
[UI](#getting-started)
```
___
*[`site/learn/IntroductionV2.md` line 37 at r1](https://reviewable.io/reviews/kube-HPC/kube-HPC.github.io/38#-NQR4OVPE4C5c_dc0Cu6:-NQR4OVPE4C5c_dc0Cu7:b-p3o42t) ([raw file](https://github.com/kube-HPC/kube-HPC.github.io/blob/e50cd9f1561aa2f9c54f79fddc3aa6139d623254/site/learn/IntroductionV2.md#L37)):*
> ```Markdown
> 
> ## Getting started
> - HKube is available in 3 formats, [UI](#getting-started), [CLI](/learn/api/#Cli) and [RESTFUL-API](/learn/api/#restful-api).
> ```

<s>is available in 3 formats,</s>
has



_Code quote:_
```Markdown
is available in 3 formats,
```
___
*[`site/learn/IntroductionV2.md` line 38 at r1](https://reviewable.io/reviews/kube-HPC/kube-HPC.github.io/38#-NQR5vSo10ud2Ckafv-1:-NQR5vSo10ud2Ckafv-2:b-8v7ryh) ([raw file](https://github.com/kube-HPC/kube-HPC.github.io/blob/e50cd9f1561aa2f9c54f79fddc3aa6139d623254/site/learn/IntroductionV2.md#L38)):*
> ```Markdown
> ## Getting started
> - HKube is available in 3 formats, [UI](#getting-started), [CLI](/learn/api/#Cli) and [RESTFUL-API](/learn/api/#restful-api).
> - **UI Prerequisite** - See [Install](/learn/install/) for both **local** and **production** environments
> ```

**<s>UI</s> Prerequisite** -  [Install hkube](/learn/install/) for both **local** and **production** environments



_Code quote:_
```Markdown
**UI Prerequisite** - See [Install](/learn/install/) for both **local** and **production** environments
```
___
*[`site/learn/IntroductionV2.md` line 40 at r1](https://reviewable.io/reviews/kube-HPC/kube-HPC.github.io/38#-NQR8eRW91g-ygt9jCMC:-NQR8eRW91g-ygt9jCMD:brpgmid) ([raw file](https://github.com/kube-HPC/kube-HPC.github.io/blob/e50cd9f1561aa2f9c54f79fddc3aa6139d623254/site/learn/IntroductionV2.md#L40)):*
> ```Markdown
> - **UI Prerequisite** - See [Install](/learn/install/) for both **local** and **production** environments
> 
> - **Uploading Algorithms**
> ```

<s>**Creating your first Algorithm**</s>



_Code quote:_
```Markdown
**Uploading Algorithms**
```
___
*[`site/learn/IntroductionV2.md` line 43 at r1](https://reviewable.io/reviews/kube-HPC/kube-HPC.github.io/38#-NQRBe5R2M-IX5_DM4TI:-NQRBe5R2M-IX5_DM4TJ:bvl0ybo) ([raw file](https://github.com/kube-HPC/kube-HPC.github.io/blob/e50cd9f1561aa2f9c54f79fddc3aa6139d623254/site/learn/IntroductionV2.md#L43)):*
> ```Markdown
> 
>   - Currently, we support Javascript, Python and Java **autobuild**.
>   - In order to be HKube compatiable, Algorithms must handle inputs the following way:
> ```

<s>In order to be HKube compatiable, Algorithms must handle </s>Your algorithm gets its inputs from hkube the following way:



_Code quote:_
```Markdown
In order to be HKube compatiable, Algorithms must handle inputs the following way:
```
___
*[`site/learn/IntroductionV2.md` line 65 at r1](https://reviewable.io/reviews/kube-HPC/kube-HPC.github.io/38#-NQR84GJDOaTpvnIqtUa:-NQR84GKDyvtyDdUmaQ9:b-skbj2u) ([raw file](https://github.com/kube-HPC/kube-HPC.github.io/blob/e50cd9f1561aa2f9c54f79fddc3aa6139d623254/site/learn/IntroductionV2.md#L65)):*
> ```Markdown
>     };
>     ```
>   - Using the UI, there are three ways to upload your algorithms:
> ```

 <s>Using the UI,</s>There are three ways to <s>upload</s> deliver your algorithms



_Code quote:_
```Markdown
 Using the UI, there are three ways to upload your algorithms
```
___
*[`site/learn/IntroductionV2.md` line 68 at r1](https://reviewable.io/reviews/kube-HPC/kube-HPC.github.io/38#-NQRCKKhDfsB11t7Kkbk:-NQRCKKhDfsB11t7Kkbl:bsc3szv) ([raw file](https://github.com/kube-HPC/kube-HPC.github.io/blob/e50cd9f1561aa2f9c54f79fddc3aa6139d623254/site/learn/IntroductionV2.md#L68)):*
> ```Markdown
>     AlgUpload 
>     - Via version control ( github/gitlab)
>     - Via local package - You must pack your algorithm using
> ```

<s>local package</s> packaged file



_Code quote:_
```Markdown
local package
```
___
*[`site/learn/IntroductionV2.md` line 74 at r1](https://reviewable.io/reviews/kube-HPC/kube-HPC.github.io/38#-NQR9tlTCcRb6qmmMAHC:-NQR9tlTCcRb6qmmMAHD:bvn1aex) ([raw file](https://github.com/kube-HPC/kube-HPC.github.io/blob/e50cd9f1561aa2f9c54f79fddc3aa6139d623254/site/learn/IntroductionV2.md#L74)):*
> ```Markdown
>     - Via a pre-built docker image.
>   
> ```

We need to take the packaged file option as our example and be more detailed about it, I am missing an explanation of the structure of the  algorithm project and the "entrypoint" that has to be configured.
___
*[`site/learn/IntroductionV2.md` line 107 at r1](https://reviewable.io/reviews/kube-HPC/kube-HPC.github.io/38#-NQQHR9j0IsllD_Asflm:-NQQHR9j0IsllD_Asfln:bde15pw) ([raw file](https://github.com/kube-HPC/kube-HPC.github.io/blob/e50cd9f1561aa2f9c54f79fddc3aa6139d623254/site/learn/IntroductionV2.md#L107)):*
> ```Markdown
> #### Range Algorithm
> 
> Creates an array of length `N`.
> ```

Receives a parameter N and returns an array of length N with acceding numbers. 



_Code quote:_
```Markdown
Creates an array of length `N`.
```
___
*[`site/learn/IntroductionV2.md` line 116 at r1](https://reviewable.io/reviews/kube-HPC/kube-HPC.github.io/38#-NQQHZZi1QNGkEoZjk0b:-NQQHZZi1QNGkEoZjk0c:bxag4uw) ([raw file](https://github.com/kube-HPC/kube-HPC.github.io/blob/e50cd9f1561aa2f9c54f79fddc3aa6139d623254/site/learn/IntroductionV2.md#L116)):*
> ```Markdown
> #### Multiply Algorithm
> 
> Multiples the received data from `Range Algorithm` by `k`.
> ```

Receives a parameter k and I and returns their multiplication 



_Code quote:_
```Markdown
Multiples the received data from `Range Algorithm` by `k`.
```
___
*[`site/learn/IntroductionV2.md` line 120 at r1](https://reviewable.io/reviews/kube-HPC/kube-HPC.github.io/38#-NQQI3BoEx3JEEYHF_M5:-NQQI3BoEx3JEEYHF_M6:b-gphbuy) ([raw file](https://github.com/kube-HPC/kube-HPC.github.io/blob/e50cd9f1561aa2f9c54f79fddc3aa6139d623254/site/learn/IntroductionV2.md#L120)):*
> ```Markdown
> ```console
> k = 2
> [1,2,3,4,5] * (2) -> [2,4,6,8,10]
> ```

k=2 , i = 3
2*3 -> 6



_Code quote:_
```Markdown
k = 2
[1,2,3,4,5] * (2) -> [2,4,6,8,10]
```
___
*[`site/learn/IntroductionV2.md` line 121 at r1](https://reviewable.io/reviews/kube-HPC/kube-HPC.github.io/38#-NQQIRqwBqDm6SPNtlqK:-NQQIRqwBqDm6SPNtlqL:b-ke0dva) ([raw file](https://github.com/kube-HPC/kube-HPC.github.io/blob/e50cd9f1561aa2f9c54f79fddc3aa6139d623254/site/learn/IntroductionV2.md#L121)):*
> ```Markdown
> k = 2
> [1,2,3,4,5] * (2) -> [2,4,6,8,10]
> ```
> ```

(This algorithm will be invoked in parallel for each value in the first algorithm output array)
___
*[`site/learn/IntroductionV2.md` line 137 at r1](https://reviewable.io/reviews/kube-HPC/kube-HPC.github.io/38#-NQQQ32G2vY4nLM5lsy3:-NQQQ32G2vY4nLM5lsy4:b5ukqvu) ([raw file](https://github.com/kube-HPC/kube-HPC.github.io/blob/e50cd9f1561aa2f9c54f79fddc3aa6139d623254/site/learn/IntroductionV2.md#L137)):*
> ```Markdown
> There are two ways to integrate your algorithm into HKube:
> 
> - **Seamless Integration** - As written above HKube can build your docker automatically with the HKube's websocket wrapper.
> ```

Package algorithm as file



_Code quote:_
```Markdown
Seamless Integration
```
___
*[`site/learn/IntroductionV2.md` line 138 at r1](https://reviewable.io/reviews/kube-HPC/kube-HPC.github.io/38#-NQQPpwWD-yxJvv6MhrW:-NQQPpwWD-yxJvv6MhrX:b-hh3w04) ([raw file](https://github.com/kube-HPC/kube-HPC.github.io/blob/e50cd9f1561aa2f9c54f79fddc3aa6139d623254/site/learn/IntroductionV2.md#L138)):*
> ```Markdown
> 
> - **Seamless Integration** - As written above HKube can build your docker automatically with the HKube's websocket wrapper.
> - **Code writing** - In order to add algorithm manually to HKube, you need to wrap your algorithm with HKube. HKube already has a wrappers for `python`,`javaScript`, and `java`.
> ```

Creating a docker image



_Code quote:_
```Markdown
Code writing*
```

**Review by lepilmen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-HPC/kube-HPC.github.io/38)* status: 9 of 13 files reviewed, 14 unresolved discussions (waiting on @golanha and @zivglik)

___
*[`site/learn/IntroductionV2.md` line 37 at r1](https://reviewable.io/reviews/kube-HPC/kube-HPC.github.io/38#-NQR2E8y8uGiT_rR0ZPO:-NQU8zYMCrv-jUsWlIg1:b-896fix) ([raw file](https://github.com/kube-HPC/kube-HPC.github.io/blob/e50cd9f1561aa2f9c54f79fddc3aa6139d623254/site/learn/IntroductionV2.md#L37)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

shouldn't be a link
[UI] <s>(#getting-started)</s>
</blockquote></details>

Done.
___
*[`site/learn/IntroductionV2.md` line 37 at r1](https://reviewable.io/reviews/kube-HPC/kube-HPC.github.io/38#-NQR4OVPE4C5c_dc0Cu6:-NQU9-px7YfIYoC55agI:b-896fix) ([raw file](https://github.com/kube-HPC/kube-HPC.github.io/blob/e50cd9f1561aa2f9c54f79fddc3aa6139d623254/site/learn/IntroductionV2.md#L37)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

<s>is available in 3 formats,</s>
has
</blockquote></details>

Done.
___
*[`site/learn/IntroductionV2.md` line 38 at r1](https://reviewable.io/reviews/kube-HPC/kube-HPC.github.io/38#-NQR5vSo10ud2Ckafv-1:-NQU90l56NK4_KHka0s_:b-896fix) ([raw file](https://github.com/kube-HPC/kube-HPC.github.io/blob/e50cd9f1561aa2f9c54f79fddc3aa6139d623254/site/learn/IntroductionV2.md#L38)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

**<s>UI</s> Prerequisite** -  [Install hkube](/learn/install/) for both **local** and **production** environments
</blockquote></details>

Done.
___
*[`site/learn/IntroductionV2.md` line 40 at r1](https://reviewable.io/reviews/kube-HPC/kube-HPC.github.io/38#-NQR8eRW91g-ygt9jCMC:-NQU91d-ER0d131MDGYr:b-896fix) ([raw file](https://github.com/kube-HPC/kube-HPC.github.io/blob/e50cd9f1561aa2f9c54f79fddc3aa6139d623254/site/learn/IntroductionV2.md#L40)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

<s>**Creating your first Algorithm**</s>
</blockquote></details>

Done.
___
*[`site/learn/IntroductionV2.md` line 43 at r1](https://reviewable.io/reviews/kube-HPC/kube-HPC.github.io/38#-NQRBe5R2M-IX5_DM4TI:-NQU92JCB8CWOPcLxHD7:b-896fix) ([raw file](https://github.com/kube-HPC/kube-HPC.github.io/blob/e50cd9f1561aa2f9c54f79fddc3aa6139d623254/site/learn/IntroductionV2.md#L43)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

<s>In order to be HKube compatiable, Algorithms must handle </s>Your algorithm gets its inputs from hkube the following way:
</blockquote></details>

Done.
___
*[`site/learn/IntroductionV2.md` line 65 at r1](https://reviewable.io/reviews/kube-HPC/kube-HPC.github.io/38#-NQR84GJDOaTpvnIqtUa:-NQU93Tj3kMw2DDJ4t12:b-896fix) ([raw file](https://github.com/kube-HPC/kube-HPC.github.io/blob/e50cd9f1561aa2f9c54f79fddc3aa6139d623254/site/learn/IntroductionV2.md#L65)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

 <s>Using the UI,</s>There are three ways to <s>upload</s> deliver your algorithms
</blockquote></details>

Done.
___
*[`site/learn/IntroductionV2.md` line 68 at r1](https://reviewable.io/reviews/kube-HPC/kube-HPC.github.io/38#-NQRCKKhDfsB11t7Kkbk:-NQU94aM12q2RZRagXLP:b-896fix) ([raw file](https://github.com/kube-HPC/kube-HPC.github.io/blob/e50cd9f1561aa2f9c54f79fddc3aa6139d623254/site/learn/IntroductionV2.md#L68)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

<s>local package</s> packaged file
</blockquote></details>

Done.
___
*[`site/learn/IntroductionV2.md` line 74 at r1](https://reviewable.io/reviews/kube-HPC/kube-HPC.github.io/38#-NQR9tlTCcRb6qmmMAHC:-NQU94ss1AwOnROmMbrO:b-3hmvwh) ([raw file](https://github.com/kube-HPC/kube-HPC.github.io/blob/e50cd9f1561aa2f9c54f79fddc3aa6139d623254/site/learn/IntroductionV2.md#L74)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

We need to take the packaged file option as our example and be more detailed about it, I am missing an explanation of the structure of the  algorithm project and the "entrypoint" that has to be configured.
</blockquote></details>

Added a section further explaining the expected package content, and also note the "entry point", with an image helping the user to understand the topic.
___
*[`site/learn/IntroductionV2.md` line 107 at r1](https://reviewable.io/reviews/kube-HPC/kube-HPC.github.io/38#-NQQHR9j0IsllD_Asflm:-NQU9H5-3UmYVHHGO4YZ:b-896fix) ([raw file](https://github.com/kube-HPC/kube-HPC.github.io/blob/e50cd9f1561aa2f9c54f79fddc3aa6139d623254/site/learn/IntroductionV2.md#L107)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

Receives a parameter N and returns an array of length N with acceding numbers. 
</blockquote></details>

Done.
___
*[`site/learn/IntroductionV2.md` line 116 at r1](https://reviewable.io/reviews/kube-HPC/kube-HPC.github.io/38#-NQQHZZi1QNGkEoZjk0b:-NQU9JOsCIryG2fCtdeN:b-896fix) ([raw file](https://github.com/kube-HPC/kube-HPC.github.io/blob/e50cd9f1561aa2f9c54f79fddc3aa6139d623254/site/learn/IntroductionV2.md#L116)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

Receives a parameter k and I and returns their multiplication 
</blockquote></details>

Done.
___
*[`site/learn/IntroductionV2.md` line 120 at r1](https://reviewable.io/reviews/kube-HPC/kube-HPC.github.io/38#-NQQI3BoEx3JEEYHF_M5:-NQU9JmlD3OJNB2hrr3k:b-896fix) ([raw file](https://github.com/kube-HPC/kube-HPC.github.io/blob/e50cd9f1561aa2f9c54f79fddc3aa6139d623254/site/learn/IntroductionV2.md#L120)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

k=2 , i = 3
2*3 -> 6
</blockquote></details>

Done.
___
*[`site/learn/IntroductionV2.md` line 121 at r1](https://reviewable.io/reviews/kube-HPC/kube-HPC.github.io/38#-NQQIRqwBqDm6SPNtlqK:-NQU9K8NEhIamiCSvcg3:bvm16av) ([raw file](https://github.com/kube-HPC/kube-HPC.github.io/blob/e50cd9f1561aa2f9c54f79fddc3aa6139d623254/site/learn/IntroductionV2.md#L121)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

(This algorithm will be invoked in parallel for each value in the first algorithm output array)
</blockquote></details>

Added, after every explanation of an algorithm, a note on what is it's part in our pipeline.
___
*[`site/learn/IntroductionV2.md` line 137 at r1](https://reviewable.io/reviews/kube-HPC/kube-HPC.github.io/38#-NQQQ32G2vY4nLM5lsy3:-NQU9SZGAVklYOCkwP0X:b-896fix) ([raw file](https://github.com/kube-HPC/kube-HPC.github.io/blob/e50cd9f1561aa2f9c54f79fddc3aa6139d623254/site/learn/IntroductionV2.md#L137)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

Package algorithm as file
</blockquote></details>

Done.
___
*[`site/learn/IntroductionV2.md` line 138 at r1](https://reviewable.io/reviews/kube-HPC/kube-HPC.github.io/38#-NQQPpwWD-yxJvv6MhrW:-NQU9Sk18tkhdDO3N9CY:b-896fix) ([raw file](https://github.com/kube-HPC/kube-HPC.github.io/blob/e50cd9f1561aa2f9c54f79fddc3aa6139d623254/site/learn/IntroductionV2.md#L138)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

Creating a docker image
</blockquote></details>

Done.

**Review by golanha — APPROVED** [review]
> Reviewed 2 of 12 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-HPC/kube-HPC.github.io/38)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @zivglik)

**Review by golanha — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/kube-HPC/kube-HPC.github.io/38#-:-NQyJptF8t9PtrSEb4We:bnfp4nl)* status: 0 of 13 files reviewed, all discussions resolved

**Review by golanha — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/kube-HPC/kube-HPC.github.io/38#-:-NQyK6Dw6rhyKu2Hpcxz:bnfp4nl)* status: 0 of 13 files reviewed, all discussions resolved

**Review by golanha — APPROVED** [review]
> Reviewed 11 of 12 files at r1, 1 of 2 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-HPC/kube-HPC.github.io/38)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lepilmen)

**Pull request merged**
