### PR TITLE
added branch creation with result file

### PR DESCRIPTION
**Pull request by RonShvarz**
This change is [Reviewable](https://reviewable.io/reviews/kube-HPC/kube-HPC.github.io/48)

### CODE REVIEW

**Comment by RonShvarz** [comment]
kube-HPC/hkube#1753

**Review by golanha — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-HPC/kube-HPC.github.io/48)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @RonShvarz)

___
*[`.github/workflows/trivy.yaml` line 54 at r1](https://reviewable.io/reviews/kube-HPC/kube-HPC.github.io/48#-NdxdMGt4m9wML1AeJ8W:-NdxdMGt4m9wML1AeJ8X:b4y5607) ([raw file](https://github.com/kube-HPC/kube-HPC.github.io/blob/c74344307281bc7293eb0705908f05da39758e03/.github/workflows/trivy.yaml#L54)):*
> ```YAML
>           git add TrivyScans/trivy_license_image.txt
>           git add TrivyScans/trivy_vuln_image.txt
>           git commit -m "Add files to a specific folder"
> ```

put a more meaningfull message, something like "Add scan results to tryivy-scan-results"



_Code quote:_
```YAML
"Add files to a specific folder"
```
___
*[`.github/workflows/trivy.yaml` line 55 at r1](https://reviewable.io/reviews/kube-HPC/kube-HPC.github.io/48#-Ndxe_Rx8fVRqZXeFVcn:-Ndxe_Rx8fVRqZXeFVco:b-n6pfbz) ([raw file](https://github.com/kube-HPC/kube-HPC.github.io/blob/c74344307281bc7293eb0705908f05da39758e03/.github/workflows/trivy.yaml#L55)):*
> ```YAML
>           git add TrivyScans/trivy_vuln_image.txt
>           git commit -m "Add files to a specific folder"
>           git push --force origin trivy-scan-results
> ```

not nessacery



_Code quote:_
```YAML
--force
```

**Review by golanha — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-HPC/kube-HPC.github.io/48)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @RonShvarz)

___
*[`.github/workflows/main.yaml` line 89 at r2](https://reviewable.io/reviews/kube-HPC/kube-HPC.github.io/48#-Neat7pc1wKAWIiKGfpA:-Neat7pc1wKAWIiKGfpB:b-e8juki) ([raw file](https://github.com/kube-HPC/kube-HPC.github.io/blob/72bdad26bdabba8bfddfe87e1aa12d7dc85d2098/.github/workflows/main.yaml#L89)):*
> ```YAML
>             echo "branch fetched"
>             git checkout trivy-scan-results
>             git pull
> ```

redundant no need to pull right after its been fetched



_Code quote:_
```YAML
git pull
```
___
*[`.github/workflows/trivy.yaml` line 49 at r2](https://reviewable.io/reviews/kube-HPC/kube-HPC.github.io/48#-NeatZUe0u5NBi-4PAW4:-NeatZUe0u5NBi-4PAW5:bkw078s) ([raw file](https://github.com/kube-HPC/kube-HPC.github.io/blob/72bdad26bdabba8bfddfe87e1aa12d7dc85d2098/.github/workflows/trivy.yaml#L49)):*
> ```YAML
>             echo "branch fetched"
>             git checkout trivy-scan-results
>             git pull
> ```

no need for pull again



_Code quote:_
```YAML
pull
```

**Review by golanha — COMMENTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/kube-HPC/kube-HPC.github.io/48)* status: all files reviewed, 2 unresolved discussions (waiting on @RonShvarz)

**Pull request merged**
